//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JdmDepot.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JdmDepot.UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance (4M40).
        /// </summary>
        internal static string _4M40_Maintenance {
            get {
                return ResourceManager.GetString("4M40_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Auto Parts.
        /// </summary>
        internal static string AdvanceAuto_Text {
            get {
                return ResourceManager.GetString("AdvanceAuto_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon.
        /// </summary>
        internal static string Amazon_Text {
            get {
                return ResourceManager.GetString("Amazon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JDM Depot.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belts.
        /// </summary>
        internal static string Belts_Title {
            get {
                return ResourceManager.GetString("Belts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. Part #.
        /// </summary>
        internal static string BeltsTable_AlternativePartNumbers_Text {
            get {
                return ResourceManager.GetString("BeltsTable_AlternativePartNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string BeltsTable_Links_Text {
            get {
                return ResourceManager.GetString("BeltsTable_Links_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Part #.
        /// </summary>
        internal static string BeltsTable_ManufacturerPartNumber_Text {
            get {
                return ResourceManager.GetString("BeltsTable_ManufacturerPartNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BeltsTable_Name_Text {
            get {
                return ResourceManager.GetString("BeltsTable_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string BeltsTable_Notes_Text {
            get {
                return ResourceManager.GetString("BeltsTable_Notes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters_Title {
            get {
                return ResourceManager.GetString("Filters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. Part #.
        /// </summary>
        internal static string FiltersTable_AlternativePartNumbers_Text {
            get {
                return ResourceManager.GetString("FiltersTable_AlternativePartNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string FiltersTable_Links_Text {
            get {
                return ResourceManager.GetString("FiltersTable_Links_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Part #.
        /// </summary>
        internal static string FiltersTable_ManufacturerPartNumber_Text {
            get {
                return ResourceManager.GetString("FiltersTable_ManufacturerPartNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FiltersTable_Name_Text {
            get {
                return ResourceManager.GetString("FiltersTable_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string FiltersTable_Notes_Text {
            get {
                return ResourceManager.GetString("FiltersTable_Notes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluids.
        /// </summary>
        internal static string Fluids_Title {
            get {
                return ResourceManager.GetString("Fluids_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity (Liters).
        /// </summary>
        internal static string FluidsTable_CapacityLiters_Text {
            get {
                return ResourceManager.GetString("FluidsTable_CapacityLiters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity (Quarts).
        /// </summary>
        internal static string FluidsTable_CapacityQuarts_Text {
            get {
                return ResourceManager.GetString("FluidsTable_CapacityQuarts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string FluidsTable_Links_Text {
            get {
                return ResourceManager.GetString("FluidsTable_Links_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FluidsTable_Name_Text {
            get {
                return ResourceManager.GetString("FluidsTable_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string FluidsTable_Notes_Text {
            get {
                return ResourceManager.GetString("FluidsTable_Notes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Specification.
        /// </summary>
        internal static string FluidsTable_OriginalSpec_Text {
            get {
                return ResourceManager.GetString("FluidsTable_OriginalSpec_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePage_LinkText {
            get {
                return ResourceManager.GetString("HomePage_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no maintenance items found..
        /// </summary>
        internal static string Maintenance_NoItemsFound {
            get {
                return ResourceManager.GetString("Maintenance_NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MK2 Mitsubishi Pajero.
        /// </summary>
        internal static string MK2_Mitsubishi_Pajero {
            get {
                return ResourceManager.GetString("MK2_Mitsubishi_Pajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MK2 Mitsubishi Pajero 4M40 Maintenance.
        /// </summary>
        internal static string MK2_Mitsubishi_Pajero_4M40_Maintenance {
            get {
                return ResourceManager.GetString("MK2_Mitsubishi_Pajero_4M40_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} quarts / {1} liters.
        /// </summary>
        internal static string QuartsFormat {
            get {
                return ResourceManager.GetString("QuartsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RockAuto.
        /// </summary>
        internal static string RockAuto_Text {
            get {
                return ResourceManager.GetString("RockAuto_Text", resourceCulture);
            }
        }
    }
}
