name: "Release TEST"

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "The tag to release"
        required: true
        type: string
        default: "main"
      # target_arch:
      #   description: "The target architecture to build for"
      #   required: true
      #   type: string
      #   default: "linux/arm64"

# Allow one run of this workflow per branch and cancel existing runs if triggered again
concurrency:
  group: jdmdepot-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: kyleratti/actions/.github/actions/build-container@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # gihub_repository: ${{ github.repository }}
          project_id: "JdmDepot"
          release_tag: ${{ github.event.inputs.release_tag }}
          ssh_deploy_host: ${{ secrets.SSH_DEPLOY_HOST }}
          ssh_deploy_port: ${{ secrets.SSH_DEPLOY_PORT }}
          ssh_deploy_user: ${{ secrets.SSH_DEPLOY_USER }}
          ssh_deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          docker_compose_file: ${{ vars.DOCKER_COMPOSE_FILE }}
